name: Grobid XML checker
on:
  push:
    branches:
      - parser_validation_needed
  workflow_dispatch:
jobs:
  grobid_xml_checker:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "test"
          pip install -r ./toolbox/xml_checker/requirements.txt
      - name: run grobid_xml_checker
        env:
          DATASETS_DIR: ${{ github.workspace }}/datasets
          XSD_DIR: ${{ github.workspace }}/toolbox/xml_checker/xsd
        run: |
          echo $ROOT_DIR
          python3 ./toolbox/xml_checker/cli_xml_checker.py validate $DATASETS_DIR $XSD_DIR